/**
 * Employee directory used by the searchable dropdowns on the form.
 * Generated from Finance_team_filled.xlsx (70 people).
 *
 * To update: edit this list and re-upload this one file to GitHub. Keys are
 * short on purpose (n = name, d = department, e = email) to keep the file small.
 *
 * Anyone not in this list can still fill the form — the dropdowns suggest,
 * they do not restrict. Typing a name that is not here is allowed.
 */
window.DIRECTORY = [
  {n:"Aemorn Maneechot", d:"MA", e:"aemorn_m@banpu.co.th"},
  {n:"Arisara Sakulkarawek", d:"CFO", e:"arisara_s@banpu.co.th"},
  {n:"Atthachai Unthale", d:"Finance System", e:"atthachai_u@banpu.co.th"},
  {n:"Aunyada Suwannapong", d:"Finance Accounting and Compliance 1", e:"aunyada_s@banpu.co.th"},
  {n:"Bancha Jiralappol", d:"MA", e:"bancha_j@banpu.co.th"},
  {n:"Chanisara Khorsawat", d:"Tax Planning and Compliance", e:"chanisara_k@banpu.co.th"},
  {n:"Danielle Chaoduree", d:"Financial Risks Management", e:"danielle_c@banpu.co.th"},
  {n:"Ekachai Chanthet", d:"Finance System", e:"ekachai_c@banpu.co.th"},
  {n:"Goragoch Siriton", d:"Finance Accounting and Compliance 1", e:"goragoch_si@banpu.co.th"},
  {n:"Jeeranuch Jansakul", d:"Enterprise Risk Management", e:"jeeranuch_j@banpu.co.th"},
  {n:"Jilmiga Pusiri", d:"Treasury Operation", e:"jilmiga_p@banpu.co.th"},
  {n:"Jiraphan Boonprakob", d:"Conso", e:"jiraphan_b@banpu.co.th"},
  {n:"Jiraporn Howanich", d:"Conso", e:"jiraporn_h@banpu.co.th"},
  {n:"Jitlada Limposri", d:"Finance Accounting and Compliance 2", e:"jitlada_l@banpu.co.th"},
  {n:"Kamoltip Chalermboon", d:"Finance Accounting and Compliance 3", e:"kamoltip_c@banpu.co.th"},
  {n:"Kanlayanee Vongkusolkit", d:"Funding Strategy", e:"kanlayanee_v@banpu.co.th"},
  {n:"Kanutnun Sittiwongrut", d:"Conso", e:"kanutnun_s@banpu.co.th"},
  {n:"Korapin Suphanphayap", d:"Finance Secretary", e:"korapin_s@banpu.co.th"},
  {n:"Laaurat Jongthitinon", d:"MA", e:"laaurat_j@banpu.co.th"},
  {n:"Lawan Rojratanawichit", d:"Finance Accounting and Compliance 1", e:"lawan_r@banpu.co.th"},
  {n:"Lullnaphat Ovartvijai", d:"Finance Accounting and Compliance 4", e:"lullnaphat_o@banpu.co.th"},
  {n:"Manoch Naksanong", d:"Tax Planning and Compliance", e:"manoch_n@banpu.co.th"},
  {n:"Mayurachat Kongkham", d:"Finance Accounting and Compliance 2", e:"mayurachat_k@banpu.co.th"},
  {n:"Nerisa Chantong", d:"Tax Planning and Compliance", e:"nerisa_c@banpu.co.th"},
  {n:"Nichapat Ruengvitthayanukoh", d:"Enterprise Risk Management", e:"nichapat_r@banpu.co.th"},
  {n:"Nuntaporn Ngamwiwi", d:"Conso", e:""},
  {n:"Nutvadee Jirapongwattana", d:"Finance Accounting and Compliance 3", e:"nutvadee_j@banpu.co.th"},
  {n:"Panatchakorn Pragobpran", d:"Treasury Operation", e:"panatchakorn_p@banpu.co.th"},
  {n:"Panyawut Prangchan", d:"Finance Accounting and Compliance 4", e:"panyawut_p@banpu.co.th"},
  {n:"Patchaploy Thumthanasiri", d:"Finance Accounting and Compliance 4", e:"patchaploy_t@banpu.co.th"},
  {n:"Patchara Chaiduangmas", d:"Enterprise Risk Management", e:"patchara_c@banpu.co.th"},
  {n:"Patcharaporn Boonto", d:"Tax Planning and Compliance", e:"patcharaporn_b@banpu.co.th"},
  {n:"Pattanasak Kaenjunda", d:"Treasury Compliance", e:"pattanasak_k@banpu.co.th"},
  {n:"Pattarakan Wongjak", d:"Treasury Operation", e:"pattarakan_w@banpu.co.th"},
  {n:"Pattaraporn Pothisoda", d:"Finance Accounting and Compliance 3", e:"pattaraporn_p@banpu.co.th"},
  {n:"Pawinee Santasnachok", d:"Finance Accounting and Compliance 1", e:"pawinee_s@banpu.co.th"},
  {n:"Phayao Suksawang", d:"Conso", e:"phayao_s@banpu.co.th"},
  {n:"Pichai Maddin", d:"Treasury Operation", e:"pichai_m@banpu.co.th"},
  {n:"Pichaya Pengchan", d:"Treasury Operation", e:"pichaya_p@banpu.co.th"},
  {n:"Pimchanok Patyen", d:"Financial Risks Management", e:"pimchanok_p@banpu.co.th"},
  {n:"Piyanuch Trisakulwatthana", d:"Group Controller", e:"piyanuch_t@banpu.co.th"},
  {n:"Pornchanok Chaisiri", d:"Finance Accounting and Compliance 1", e:"pornchanok_c@banpu.co.th"},
  {n:"Pornpen Pornpakkul", d:"Finance Accounting and Compliance 1", e:"pornpen_p@banpu.co.th"},
  {n:"Prapatsorn Konghin", d:"MA", e:"prapatsorn_k@banpu.co.th"},
  {n:"Praphawan Uaamporn", d:"Financial Risks Management", e:"praphawan_u@banpu.co.th"},
  {n:"Promporn Srisawat", d:"Asset Liability Management", e:"promporn_s@banpu.co.th"},
  {n:"Ratchadaporn Mhuakmanee", d:"Finance Accounting and Compliance 2", e:"ratchadaporn_m@banpu.co.th"},
  {n:"Rungrudee Hongviwat", d:"Finance System", e:"rungrudee_h@banpu.co.th"},
  {n:"Rungtip Tunwutibundit", d:"Asset Liability Management", e:"rungtip_t@banpu.co.th"},
  {n:"Samathi Setthasakamphon", d:"Finance System", e:"samathi_s@banpu.co.th"},
  {n:"Saranrat Khongwattananon", d:"Finance Accounting and Compliance 4", e:"saranrat_k@banpu.co.th"},
  {n:"Sarisa Phupa", d:"MA", e:"sarisa_p@banpu.co.th"},
  {n:"Sattabongkot Chumanee", d:"Treasury Operation", e:"sattabongkot_c@banpu.co.th"},
  {n:"Sirima Pongpaw", d:"MA", e:"sirima_p@banpu.co.th"},
  {n:"Siriphat Prangchan", d:"Finance Accounting and Compliance 1", e:"siriphat_p@banpu.co.th"},
  {n:"Supakanda Boonjunwetvat", d:"Tax Planning and Compliance", e:"supakanda_b@banpu.co.th"},
  {n:"Supawadee Sagen", d:"Finance Accounting and Compliance 1", e:"supawadee_sa@banpu.co.th"},
  {n:"Surapha Thamwiset", d:"Asset Liability Management", e:"surapha_t@banpu.co.th"},
  {n:"Suttana Bokhuntod", d:"Conso", e:"suttana_b@banpu.co.th"},
  {n:"Thanyaluk Kanasub", d:"Enterprise Risk Management", e:"thanyaluk_k@banpu.co.th"},
  {n:"Thanyaporn Chirapiwat", d:"Finance Accounting and Compliance 1", e:"thanyaporn_c@banpu.co.th"},
  {n:"Usanee Wiwatchaiwong", d:"Enterprise Risk Management", e:"usanee_w@banpu.co.th"},
  {n:"Varunya Mooktharagosa", d:"Conso", e:"varunya_m@banpu.co.th"},
  {n:"Viriya Mekaroonvidhya", d:"Group Controller", e:"viriya_m@banpu.co.th"},
  {n:"Wanasma Waehama", d:"Finance Accounting and Compliance 1", e:"wanasma_w@banpu.co.th"},
  {n:"Watthanawipha Phochano", d:"Treasury Operation", e:"watthanawipha_p@banpu.co.th"},
  {n:"Wishuda Limpattaracharoen", d:"Corporate Controller", e:"wishuda_l@banpu.co.th"},
  {n:"Yanabhaksinee Seeha-ampai", d:"Funding Strategy", e:"yanabhaksinee_s@banpu.co.th"},
  {n:"Yanisa Kaewchoosen", d:"Finance Accounting and Compliance 1", e:"yanisa_k@banpu.co.th"},
  {n:"Yodkhwan Navagan", d:"Finance Accounting and Compliance 2", e:"yodkhwan_n@banpu.co.th"},
];
