/**
 * Shared AI Tool recommendation engine.
 * Isomorphic: usable in the browser (window.RecommendationEngine), in Node.js
 * (module.exports), and in Google Apps Script (globalThis) so the client-side
 * preview and the server-side canonical calculation can NEVER drift out of sync.
 *
 * IMPORTANT: the server is always the source of truth. The browser only uses this
 * module to show a live preview before submission; Apps Script re-runs the same
 * functions against the submitted answers before writing a row to the Sheet, so a
 * tampered browser cannot lie about its own classification or approval requirement.
 *
 * apps-script/Code.gs embeds a byte-identical copy of this file, generated by
 * build-apps-script.js — edit THIS file, then re-run that script. Never hand-edit
 * the copy inside Code.gs.
 */
(function (root, factory) {
  var mod = factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = mod;
  }
  if (typeof window !== 'undefined') {
    window.RecommendationEngine = mod;
  }
  if (typeof globalThis !== 'undefined') {
    globalThis.RecommendationEngine = mod;
  }
})(this, function () {

  var TOOLS = {
    copilot_chat:   { name: 'Microsoft 365 Copilot Chat', suitable: 'General Q&A, writing, brainstorming', workData: 'No', approval: 'No', platform: 'copilot', level: 1 },
    m365_copilot:   { name: 'Microsoft 365 Copilot', suitable: 'Email, Teams, Excel, Word, PowerPoint, Meetings', workData: 'Yes', approval: 'Depending on policy', platform: 'copilot', level: 2 },
    copilot_cowork: { name: 'Copilot Cowork', suitable: 'Multi-step execution, workflow automation, advanced tasks', workData: 'Yes', approval: 'Required', platform: 'copilot', level: 3 },
    claude_team:    { name: 'Claude Team', suitable: 'General analysis, content creation', workData: 'No confidential data', approval: 'Depending on policy', platform: 'claude', level: 1 },
    claude_code:    { name: 'Claude Code', suitable: 'Development and coding support', workData: 'No confidential data', approval: 'Required', platform: 'claude', level: 3 },
    claude_cowork:  { name: 'Claude Cowork', suitable: 'Advanced reasoning, coding, agent tasks', workData: 'No confidential data', approval: 'Required', platform: 'claude', level: 3 },
  };

  var MANDATORY_APPROVAL_TOOLS = ['copilot_cowork', 'claude_cowork', 'claude_code'];

  /**
   * The Section 2.1 questions.
   *
   *  key      what gets stored in the Sheet's ConfidentialAnswers JSON. Treat as
   *           permanent: renaming one makes old rows harder to compare.
   *  label    Thai heading shown to the person filling in the form.
   *  examples concrete instances, naming the actual systems Finance uses
   *           (Coupa, Oracle R12, TM1, BPC) so nobody has to guess which
   *           bucket their data falls in.
   *
   * Consolidated from an earlier 10-question list plus 3 proposed additions
   * (13 in total) down to 7, by merging questions that were only distinguished
   * by audience or by which team held the data -- neither of which changed the
   * outcome. Nothing was dropped: every example from the long list appears
   * under one of these seven.
   */
  var CONFIDENTIAL_FIELDS = [
    {
      key: 'Financial & Budget Data',
      label: 'ข้อมูลการเงินและงบประมาณ',
      examples: 'งบการเงิน, รายได้/กำไร-ขาดทุน, GL/Journal entries, ผังบัญชี · AP (invoice supplier, payment run), ' +
                'AR (invoice ลูกค้า, aging report) · ทะเบียนทรัพย์สิน/ค่าเสื่อมราคา · ภาษี (ภ.พ.30, ภ.ง.ด.) · ' +
                'เงินสด-ธนาคาร, เลขบัญชี, การโอนเงิน · งบประมาณและประมาณการยอดขาย/ต้นทุนล่วงหน้า ' +
                '— Oracle R12 (GL/AP/AR/FA), Coupa (invoice, payment), TM1',
    },
    {
      key: 'Contracts & Vendor Terms',
      label: 'สัญญาและเงื่อนไขคู่ค้า',
      examples: 'สัญญาจ้าง, สัญญาซื้อขาย, NDA, MOU · ราคาที่เจรจากับ supplier, quotation, เงื่อนไขการต่อรอง ' +
                '— Coupa (sourcing, PR/PO)',
    },
    {
      key: 'Personal Data (PDPA)',
      label: 'ข้อมูลส่วนบุคคล (PDPA)',
      examples: 'เงินเดือน, ข้อมูลส่วนตัวพนักงาน, ผลประเมินผลงาน · รายชื่อ/ข้อมูลติดต่อลูกค้า, ประวัติการซื้อ · ' +
                'ชื่อและข้อมูลติดต่อผู้แทนฝั่ง supplier · ผลสำรวจที่ระบุตัวบุคคลได้',
    },
    {
      key: 'Internal & Management Reports',
      label: 'รายงานภายในและรายงานผู้บริหาร',
      examples: 'รายงานประจำเดือน/ประจำไตรมาสที่ใช้ภายในทีม · รายงานเสนอผู้บริหารระดับสูง, board deck',
    },
    {
      key: 'Strategic / Pre-disclosure (MNPI)',
      label: 'ข้อมูลเชิงกลยุทธ์ / ยังไม่เปิดเผยต่อตลาด',
      examples: 'แผนควบรวมกิจการ (M&A), แผนขยายธุรกิจ · ผลประกอบการก่อนประกาศต่อตลาดหลักทรัพย์ · ' +
                'ธุรกรรมระหว่างบริษัทในเครือ, งบ consolidation กลุ่ม — BPC ' +
                '⚠️ ข้อนี้มีประเด็นทางกฎหมายเรื่อง insider trading ไม่ใช่แค่นโยบายภายใน',
    },
    {
      key: 'Audit & Internal Control',
      label: 'ผลตรวจสอบและการควบคุมภายใน',
      examples: 'ผลการตรวจสอบภายใน/ผู้สอบบัญชี · ประเด็นการควบคุมภายใน, ข้อสังเกตที่ยังไม่ปิด · เรื่องร้องเรียน',
    },
    {
      key: 'System, Code & Credentials',
      label: 'ระบบ โค้ด และข้อมูลเชื่อมต่อ',
      examples: 'โค้ดโปรแกรม, ไฟล์ configuration ของระบบภายใน · ข้อมูล export ตรงจากฐานข้อมูล ' +
                '(raw table, SQL extract) จาก Oracle R12 / TM1 / BPC · credential, รหัส, หรือ config ' +
                'ที่ใช้เชื่อมต่อระบบ',
    },
  ];

  // Just the stored keys, for code that only needs the names.
  var CONFIDENTIAL_KEYS = CONFIDENTIAL_FIELDS.map(function (f) { return f.key; });

  var ACTIVITIES = [
    { id: 'draft_email',        label: 'Draft Email',            level: 1, tool: 'copilot_chat' },
    { id: 'translation',        label: 'Translation',            level: 1, tool: 'copilot_chat' },
    { id: 'meeting_summary',    label: 'Meeting Summary',        level: 1, tool: 'm365_copilot' },
    { id: 'doc_summary',        label: 'Document Summary',       level: 1, tool: 'copilot_chat' },
    { id: 'search_files',       label: 'Search Company Files',   level: 2, tool: 'm365_copilot' },
    { id: 'analyze_excel',      label: 'Analyze Excel',          level: 2, tool: 'm365_copilot' },
    { id: 'analyze_financial',  label: 'Analyze Financial Data', level: 2, tool: 'm365_copilot' },
    { id: 'create_ppt',         label: 'Create PowerPoint',      level: 2, tool: 'm365_copilot' },
    { id: 'contract_review',    label: 'Contract Review',        level: 2, tool: 'm365_copilot' },
    { id: 'create_reports',     label: 'Create Reports',         level: 2, tool: 'm365_copilot' },
    { id: 'workflow_automation',label: 'Workflow Automation',    level: 3, tool: 'copilot_cowork' },
    { id: 'agent_creation',     label: 'Agent Creation',         level: 3, tool: 'copilot_cowork' },
    { id: 'coding',             label: 'Coding / Script Creation', level: 3, tool: 'claude_code' },
    { id: 'multistep',          label: 'Multi-step Execution',   level: 3, tool: 'copilot_cowork' },
    { id: 'process_automation', label: 'Process Automation',     level: 3, tool: 'copilot_cowork' },
  ];

  function activityById(id) {
    for (var i = 0; i < ACTIVITIES.length; i++) if (ACTIVITIES[i].id === id) return ACTIVITIES[i];
    return null;
  }

  function computeClassification(confidential) {
    confidential = confidential || {};
    // ANY 'yes' means confidential -- deliberately not limited to the current
    // question keys. A browser running a cached older version of the form sends
    // the OLD question names; matching only today's names would classify those
    // answers as non-confidential and hand the person a Claude tool for data
    // they just told us was sensitive. That is the one mistake this function
    // must never make, so it errs toward 'confidential' instead.
    for (var k in confidential) {
      if (Object.prototype.hasOwnProperty.call(confidential, k) &&
          String(confidential[k]).toLowerCase() === 'yes') {
        return 'confidential';
      }
    }
    return 'non-confidential';
  }

  function computeLevel(activityIds) {
    activityIds = activityIds || [];
    var max = 0;
    activityIds.forEach(function (id) {
      var a = activityById(id);
      if (a && a.level > max) max = a.level;
    });
    return max;
  }

  function unique(arr) {
    var seen = {}, out = [];
    arr.forEach(function (v) { if (!seen[v]) { seen[v] = true; out.push(v); } });
    return out;
  }

  function computeRequiredTools(activityIds, classification) {
    activityIds = activityIds || [];
    var rawTools = unique(activityIds.map(function (id) {
      var a = activityById(id);
      return a ? a.tool : null;
    }).filter(Boolean));

    var restricted = false;
    var finalTools = rawTools.map(function (t) {
      if (classification === 'confidential' && TOOLS[t] && TOOLS[t].platform === 'claude') {
        restricted = true;
        return 'copilot_cowork';
      }
      return t;
    });
    return { tools: unique(finalTools), restricted: restricted, rawTools: rawTools };
  }

  function computeApproval(level, tools, overrideTool, classification) {
    tools = tools || [];
    var usesMandatoryTool = tools.some(function (t) { return MANDATORY_APPROVAL_TOOLS.indexOf(t) > -1; }) ||
      (overrideTool && MANDATORY_APPROVAL_TOOLS.indexOf(overrideTool) > -1);
    var policyException = !!(overrideTool && classification === 'confidential' && TOOLS[overrideTool] && TOOLS[overrideTool].platform === 'claude');

    var required, reason;
    if (policyException) {
      required = true;
      reason = 'Policy Exception: overridden to a Claude tool while data is confidential — requires special approval.';
    } else if (level === 3 || usesMandatoryTool) {
      required = true;
      reason = 'AI Level 3 and/or a mandatory-approval tool is involved (Copilot Cowork / Claude Cowork / Claude Code).';
    } else if (level === 2) {
      required = 'optional';
      reason = 'AI Level 2 — approval is optional / policy-driven per Business Unit.';
    } else {
      required = false;
      reason = 'AI Level 1 — no approval required.';
    }
    return { required: required, reason: reason, level: level };
  }

  return {
    TOOLS: TOOLS,
    ACTIVITIES: ACTIVITIES,
    CONFIDENTIAL_FIELDS: CONFIDENTIAL_FIELDS,
    CONFIDENTIAL_KEYS: CONFIDENTIAL_KEYS,
    MANDATORY_APPROVAL_TOOLS: MANDATORY_APPROVAL_TOOLS,
    activityById: activityById,
    computeClassification: computeClassification,
    computeLevel: computeLevel,
    computeRequiredTools: computeRequiredTools,
    computeApproval: computeApproval,
  };
});
